spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.cloud.gcp.credentials.location=file:src/main/resources/gcp-credentials.json
spring.cloud.gcp.pubsub.project-id=akash-cloud-inventory-solu
server.port=8081